### ISSUE TITLE
Results table does not format correctly

### ISSUE THREAD

**Issue by mooper60** [GustavoFernandes/order-splitter#23]
When an order has both long names and short names, the resulting table's columns are not aligned properly (after copying it from the table and into a preformatted block in rocketchat).

Example:
https://gustavofernandes.github.io/order-splitter/index.html?tax=3.85&fee=4.78&tip=15&Gus=10&Larry=5&Melody=10&Austin=10&Nathaniel=6&Benjamin=9.25&Daniel=10

Result: 
```
Gus	$12.82
Larry	$6.75
Melody	$12.82
Austin	$12.82
Nathaniel	$7.97
Benjamin	$11.91
Daniel	$12.82
```

**Comment by GustavoFernandes** [comment]
Surrounding it in triple grave accents (```) does this
```
Gus	$12.82
Larry	$6.75
Melody	$12.82
Austin	$12.82
Nathaniel	$7.97
Benjamin	$11.91
Daniel	$12.82
```

**Comment by billy-hardy** [comment]
I've had this same issue

![image](https://cloud.githubusercontent.com/assets/4296754/21431934/618b204c-c837-11e6-8508-9bc5ccfaca45.png)

**Comment by jonsmithers** [comment]
Tabs vs spaces. Spaces win.
