### ISSUE TITLE
No longer deploy source

### ISSUE THREAD

**Issue by billy-hardy** [GustavoFernandes/order-splitter#24]
You can use gulp, grunt or even just npm to run build tasks that can consolidate js files, reducing the number of round trips that pages have to make. You can also incorporate transpiling to earlier JS version, expanding the supported devices

**Comment by jonsmithers** [comment]
What if had had the traditional `dist/` and `src/` directories, and served both to github pages. Then we could have a "stable" url and a "latest" url.

```
https://gustavofernandes.github.io/order-splitter/      # redirects to ./dist/
https://gustavofernandes.github.io/order-splitter/dist/ # minified stable version
https://gustavofernandes.github.io/order-splitter/src/  # unminified "dev"
```

Project structure:

```
index.html (just redirects to ./dist/index.html)
dist/
└── index.html (minified)
src/
└── index.html
```

**Comment by GustavoFernandes** [comment]
@jonsmithers I don't see a need to deploy possibly-unstable source code when dealing with real-world money exchange. There would also need to be distinctions made when an split order goes public saying that it was calculated on an experimental branch.
