### ISSUE TITLE
Allow for tip to be entered as both percentage and actual decimal value

### ISSUE THREAD

**Issue by GustavoFernandes** [GustavoFernandes/order-splitter#25]
- [x] Allow user to select format
- [x] remember user's choice

**Comment by bugg123** [comment]
Hooray yes this!

**Comment by GustavoFernandes** [comment]
Here are some suggestions on how to implement this feature.

![suggestions for issue 25](https://cloud.githubusercontent.com/assets/5157459/23335463/03264e66-fb84-11e6-860f-bb0bf57c41c1.png)

I'm also open to other ideas. Which do you think is the best approach?

**Comment by mooper60** [comment]
I'd prefer the first method (A). Seems more practical.

**Comment by jonsmithers** [comment]
**C)** ?

<img width="412" alt="screen shot 2017-02-25 at 6 41 46 pm" src="https://cloud.githubusercontent.com/assets/2660313/23335761/21171486-fb8a-11e6-9f41-ff75cfdda226.png">
<img width="409" alt="screen shot 2017-02-25 at 6 41 21 pm" src="https://cloud.githubusercontent.com/assets/2660313/23335762/211e6646-fb8a-11e6-840f-e8ee11271002.png">

The user's choice is remembered via localStorage or cookies or whatnot.

**Comment by GustavoFernandes** [comment]
**D)**
![percentage checkbox](https://cloud.githubusercontent.com/assets/5157459/23343072/6ef0fa88-fc33-11e6-87c0-d3855ab8e175.png)

What about simplifying and extending @jonsmithers 's idea with 1 checkbox?

**Comment by jonsmithers** [comment]
When it comes to "1 checkbox" vs "2 radio buttons", I don't think checkboxes are _always_ better. For example, if you're choosing between "pepperoni" and "sausage" for your pizza topping, should you use a checkbox or radio buttons? Probably radio buttons. I actually had a mini conversation with Tyson about this last Friday and that was the example he gave.

**Comment by GustavoFernandes** [comment]
Agreed - if you want sausage, you wouldn't expect your choices to be "check for pepperoni, un-check for not pepperoni" because sausage is not the opposite of pepperoni. It also doesn't account if you want pineapple as pizza topping. 

However, in this case, I only see 2 ways of interpreting the value of the tip field: it's either a percentage or it's not.

**Comment by bugg123** [comment]
Gus wrote pretty much exactly what I was typing on my phone.  Agreed.

**Comment by jonsmithers** [comment]
Upon further ponderment, I agree with you. Especially with a dollar sign in front...I think it's already pretty clear what the "unchecked" state indicates.

**Comment by GustavoFernandes** [comment]
This made it into `dev` before it was the default branch.
