### ISSUE TITLE
Tax percentage is incorrect.

### ISSUE THREAD

**Issue by nlanglo1** [GustavoFernandes/order-splitter#26]
The calculated tax rate is off slightly due to fees not being included in the subtotal (fees should be taxed.)

**Comment by GustavoFernandes** [comment]
@nlanglo1 It appears that if I change the tax percent calculation to be `tax / (subtotal + fees)`, the totals of everyone's costs and the actual order total aren't equal anymore. How do you mean "the calculated tax rate is off slightly"?
