### ISSUE TITLE
Whitespaces in names are not sanitized in URL

### ISSUE THREAD

**Issue by mooper60** [GustavoFernandes/order-splitter#28]
The URL provided for users to copy will contain whitespaces if the member's names have whitespaces in them. For example:

https://gustavofernandes.github.io/order-splitter/index.html?tax=5.18&fee=4.78&tip=20&JOHN DOE=9.49

**Comment by Red-Thirteen** [comment]
Do you want to replace them with `%20` or something else like dashes? 

http://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space

**Comment by GustavoFernandes** [comment]
@Red-Thirteen Probably use something along the lines of `encodeURI()` or `encodeURIComponent()` functions.
