### ISSUE TITLE
set up Linting of javascript

### ISSUE THREAD

**Issue by billy-hardy** [GustavoFernandes/order-splitter#30]
need build task

**Comment by jonsmithers** [comment]
Code editor plugins are more convenient, but build tasks work too.

<img width="327" alt="screen shot 2017-02-11 at 7 00 41 pm" src="https://cloud.githubusercontent.com/assets/2660313/22858471/793928a6-f08c-11e6-85c8-28a6422923f7.png">

**Comment by billy-hardy** [comment]
With a build task we can cause the build to fail if any code smells get in. More in your face
![image](https://cloud.githubusercontent.com/assets/4296754/22858731/b4423756-f093-11e6-8144-2801c6376e9e.png)

**Comment by GustavoFernandes** [comment]
This made it into `dev`, just didn't get closed.
